run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/example/privacy-gateway
